config/routes.rb
Rails.application.routes.draw do
  resources :months, only: [:new, :create, :show]
  resource :year, only: [:show]
  root "months#new"
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  class << self
    def artm
      find_or_create_by!(name: "artm")
    end

    def michael
      find_or_create_by!(name: "Michael")
    end

    def leon
      find_or_create_by!(name: "Leon")
    end
  end
end

app/models/week_work.rb
class WeekWork < ActiveRecord::Base
  belongs_to :employee
  has_paper_trail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :per_week, :employees, :time_travel_to

  private

  def tracked_hours
    all = WeekWork.all
    all = all.map{|ww| ww.version_at(time_travel_to)}.compact if time_travel_to
    all
  end

  def employees
    names = tracked_hours.map{|ww| ww.employee.name}.presence || Employee.pluck(:name)
    names.uniq.sort_by(&:capitalize)
  end

  def per_week
    unless @per_week
      @per_week = {}
      tracked_hours.each do |week_work|
        week = "2015 W#{week_work.week_number}"
        @per_week[week] ||= {}
        @per_week[week].merge! "week" => week, week_work.employee.name => week_work.hours
      end
    end
    @per_week
  end

  def time_travel_to
    params[:time_travel_to]
  end
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  def new
    WeekWork.paper_trail_off!
    WeekWork.delete_all
    PaperTrail::Version.delete_all
    WeekWork.paper_trail_on!
  end

  def create
    if this_year?
      SimulateTimeTracking.new(new_month_number).call
      redirect_to action: "show", id: new_month_number
    else
      redirect_to controller: "years", action: "show"
    end
  end

  private

  def new_month_number
    @new_month_number ||= params[:month][:id].to_i
  end

  def tracked_hours
    WeekWork.where(week_number: view_context.month.weeks)
  end

  def this_year?
   new_month_number <= 12
  end
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tracked_hours_graph options = {}
    type = options.delete(:type) || "Bar"
    content_tag :div, nil,
      "data-graph" => type,
      "data-graph-options" => tracked_hours_graph_defaults.merge(options).to_json
  end

  def tracked_hours_graph_defaults
    {
      data: per_week.values,
      xkey: "week",
      ykeys: employees,
      labels: employees,
      hideHover: "auto",
      postUnits: "uur",
    }
  end
end

app/helpers/months_helper.rb
module MonthsHelper
  def month_number
    params[:id].to_i
  end

  def month
    params[:id] && Month.new(2015, month_number)
  end
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    '//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= params[:controller] %>'>

<%= yield %>

  <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js' %>
  <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js' %>
  <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/months/_simulate_form.erb
<%= form_for :month, url: months_path do |f| %>
  <%= f.hidden_field :id, value: month_number + 1 %>
  <%= f.submit "Simuleer!" %>
<% end %>

app/views/months/new.html.erb
<h1>Welkom op urenregistratie simulator</h1>

<%= render "simulate_form" %>

app/views/months/show.html.erb
<h1>Geregistreerde uren voor <%= month %></h1>

<%= button_to "Opnieuw", new_month_path, method: "get" %>
<%= render "simulate_form" %>

<%= tracked_hours_graph %>

app/views/years/show.html.erb
<h1>2015 werkuren</h1>

<%- if time_travel_to %>
  <p>Geregistreerd op <%= time_travel_to %></p>
<%- end %>

<%= tracked_hours_graph(type: "Line",
                        events: Month.starts + ["2016-01"],
                        eventLineColors: ["#AAA"])
%>